version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8080}:8080"
    volumes:
      - .:/app
    env_file:
      - .env
    command: make watch
    depends_on:
      - migrate

  migrate:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["make", "migrate"]
