// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: exam_exercise.sql

package repository

import (
	"context"
)

const insertExamExercise = `-- name: InsertExamExercise :exec
INSERT INTO exams_exercises (exam_id, exercise_id) VALUES (?, ?)
`

type InsertExamExerciseParams struct {
	ExamID     int64 `json:"exam_id"`
	ExerciseID int64 `json:"exercise_id"`
}

func (q *Queries) InsertExamExercise(ctx context.Context, arg InsertExamExerciseParams) error {
	_, err := q.exec(ctx, q.insertExamExerciseStmt, insertExamExercise, arg.ExamID, arg.ExerciseID)
	return err
}
