// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"database/sql"
	"time"
)

type Exam struct {
	ID            int64        `json:"id"`
	CreatedAt     time.Time    `json:"created_at"`
	UpdatedAt     time.Time    `json:"updated_at"`
	DeletedAt     sql.NullTime `json:"deleted_at"`
	DateOfPassing time.Time    `json:"date_of_passing"`
	ExamNumber    int64        `json:"exam_number"`
	ProfessorID   int64        `json:"professor_id"`
	TemplateID    int64        `json:"template_id"`
	Foreign       interface{}  `json:"foreign"`
}

type ExamsExercise struct {
	ExamID     int64 `json:"exam_id"`
	ExerciseID int64 `json:"exercise_id"`
}

type Exercise struct {
	ID           int64        `json:"id"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
	DeletedAt    sql.NullTime `json:"deleted_at"`
	ExerciseName string       `json:"exercise_name"`
	ExercisePath string       `json:"exercise_path"`
	LessonID     int64        `json:"lesson_id"`
	UploadedBy   int64        `json:"uploaded_by"`
}

type Lesson struct {
	ID         int64        `json:"id"`
	CreatedAt  sql.NullTime `json:"created_at"`
	UpdatedAt  sql.NullTime `json:"updated_at"`
	DeletedAt  sql.NullTime `json:"deleted_at"`
	LessonName string       `json:"lesson_name"`
	Year       string       `json:"year"`
	Subject    string       `json:"subject"`
}

type Template struct {
	ID           int64        `json:"id"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
	DeletedAt    sql.NullTime `json:"deleted_at"`
	UploadedBy   int64        `json:"uploaded_by"`
	PbFileID     string       `json:"pb_file_id"`
	TemplateName string       `json:"template_name"`
}

type User struct {
	ID        int64        `json:"id"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
	FirstName string       `json:"first_name"`
	LastName  string       `json:"last_name"`
	Email     string       `json:"email"`
	Password  string       `json:"password"`
	Admin     int64        `json:"admin"`
}
