// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"database/sql"
)

type Exam struct {
	ID            int64
	CreatedAt     sql.NullTime
	UpdatedAt     sql.NullTime
	DeletedAt     sql.NullTime
	DateOfPassing sql.NullTime
	ExamNumber    sql.NullInt64
	ProfessorID   sql.NullInt64
}

type ExamsExercise struct {
	ExamID     sql.NullInt64
	ExerciseID sql.NullInt64
}

type Exercise struct {
	ID           int64
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	DeletedAt    sql.NullTime
	ExerciseName string
	ExercisePath string
	LessonID     int64
	UploadedBy   int64
}

type Lesson struct {
	ID         int64
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
	DeletedAt  sql.NullTime
	LessonName string
	Year       string
	Subject    string
}

type User struct {
	ID        int64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
	FirstName string
	LastName  string
	Email     string
	Password  string
	Admin     int64
}
